### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by francoberton** [markchen8717/Gekko_Bot_Trading_Strategies#1]
When I start the strategy in backtest mode, the strategy fails.
I followed the instructions defined in the readme.

**Comment by riesgorafael** [comment]
Hi, i have this error: 
2018-07-06 13:38:33 (DEBUG):    Prediction: NaN
2018-07-06 13:38:33 (DEBUG):    lowestRSI: 37.18953280242226
2018-07-06 13:38:33 (DEBUG):    highestRSI: 58.749660164460494
2018-07-06 13:38:33 (DEBUG):    StochRsi: 23.77865816598558
2018-07-06 13:38:33 (DEBUG):    StochRsiB: 58.538017290098004
2018-07-06 13:38:33 (DEBUG):    Actual: 4.982

**Comment by markchen8717** [comment]
> Hi, i have this error:
> 2018-07-06 13:38:33 (DEBUG): Prediction: NaN
> 2018-07-06 13:38:33 (DEBUG): lowestRSI: 37.18953280242226
> 2018-07-06 13:38:33 (DEBUG): highestRSI: 58.749660164460494
> 2018-07-06 13:38:33 (DEBUG): StochRsi: 23.77865816598558
> 2018-07-06 13:38:33 (DEBUG): StochRsiB: 58.538017290098004
> 2018-07-06 13:38:33 (DEBUG): Actual: 4.982

My apologies for the late reply. I believe that the console is informing you regards to the current state of each variable. Also, the first prediction made by the NN should be neglected because it does not yet have any backtest data, and thus, it is NaN. All in all, this shouldn't be an error message.
